name: RESOLVING CONFLICT THROUGH MEDIATION
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75405
title: Voice Of Reason Dispute Resolution
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4d8ac9'
    - '#003e6f'
    - '#79a7d6'
    - '#d2e2f1'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
