name: Voice Of Reason Dispute Resolution
favicon: null
layout_spectrum: 0.50506
typography_spectrum: 0.48915
title: Mediation and Dispute Resolution Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4d8ac9'
    - '#003e6f'
    - '#79a7d6'
    - '#d2e2f1'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
