name: Voice Of Reason Dispute Resolution
favicon: null
layout_spectrum: 0.36779210693202913
typography_spectrum: 0.7251475229859352
title: Voice Of Reason Dispute Resolution
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.648490885971114
  lightness: 0.937098732450977
  saturation: 0.5900590431410819
  rhythmicContrast: 0.3796646299306303
purpose: []
